---
title: "correlation"
author: "An Nguyen"
date: "November 13, 2017"
output: html_document
---

```{r,echo=FALSE,warning=FALSE}

library(PerformanceAnalytics)
library(readr)

tslrt <- read.csv("C:/Users/Qlab/Downloads/mturk_data/tsl_RT.csv")
vslrt <- read.csv("C:/Users/Qlab/Downloads/mturk_data/vsl_RT.csv")
sslrt <- read.csv("C:/Users/Qlab/Downloads/mturk_data/ssl_RT.csv")
lslrt <- read.csv("C:/Users/Qlab/Downloads/mturk_data/lsl_RT.csv")

tsla <- read.csv("C:/Users/Qlab/Downloads/mturk_data/tsl_acc.csv")
vsla <- read.csv("C:/Users/Qlab/Downloads/mturk_data/vsl_acc.csv")
ssla <- read.csv("C:/Users/Qlab/Downloads/mturk_data/ssl_acc.csv")
lsla <- read.csv("C:/Users/Qlab/Downloads/mturk_data/lsl_acc.csv")


scf <- read.csv("C:/Users/Qlab/Downloads/mturk_data/scf.csv")
wj3 <- read.csv("C:/Users/Qlab/Downloads/mturk_data/wj3_score.csv")


tempt <- tslrt
temps <- sslrt
tempv <- vslrt
templ <- lslrt

colnames(tempt) <- c("X","id","meanrt","rtslope","hitrate","missrate","corr","false","dp","wj3","gender","hand","lang")
colnames(temps) <- c("X","id","meanrt","rtslope","hitrate","missrate","corr","false","dp","wj3","gender","hand","lang")
colnames(tempv) <- c("X","id","meanrt","rtslope","hitrate","missrate","corr","false","dp","wj3","gender","hand","lang")
colnames(templ) <- c("X","id","meanrt","rtslope","hitrate","missrate","corr","false","dp","wj3","gender","hand","lang")

dataname <- rbind(tempt,tempv,templ,temps)
a<-NULL
for (i in (unique(dataname$id))){if(sum(dataname$id==i)==4){a<-append(a,i)}}

tempat <- tsla
tempas <- ssla
tempav <- vsla
tempal <- lsla

colnames(tempat) <- c("X","id","%_corr","cond","gender")
colnames(tempas) <- c("X","id","%_corr","cond", "gender")
colnames(tempav) <- c("X","id","%_corr","cond", "gender")
colnames(tempal) <- c("X","id","%_corr","cond", "gender")

dataname2 <- rbind(tempat,tempav,tempal,tempas)
b<-NULL
for (i in (unique(dataname2$id))){if(sum(dataname2$id==i)==4){b<-append(b,i)}}


tsl_rt_slope <- NULL
vsl_rt_slope  <- NULL
ssl_rt_slope <- NULL
lsl_rt_slope <- NULL

tsl_accuracy <- NULL
vsl_accuracy <- NULL
ssl_accuracy <- NULL
lsl_accuracy <- NULL

wj31 <- NULL 
age1 <- NULL
for (id in a) {tsl_rt_slope <-append(tsl_rt_slope,tslrt$rt_slope[tslrt$list_tsl_id==id])
vsl_rt_slope<-append(vsl_rt_slope,vslrt$rt_slope[vslrt$list_vsl_id==id])
ssl_rt_slope<-append(ssl_rt_slope,sslrt$rt_slope[sslrt$list_ssl_id==id])
lsl_rt_slope<-append(lsl_rt_slope,lslrt$rt_slope[lslrt$list_lsl_id==id])
wj31 <- append(wj31, wj3$total[wj3$ID==id])
age1 <- append(age1, scf$age[scf$ID==id])}


for (id in b) {
tsl_accuracy <- append(tsl_accuracy,tsla$subj_corr[tsla$acc_id==id])
vsl_accuracy <- append(vsl_accuracy,vsla$subj_corr[vsla$acc_id==id])
ssl_accuracy <- append(ssl_accuracy,ssla$subj_corr[ssla$acc_id==id])
lsl_accuracy <- append(lsl_accuracy,lsla$subj_corr[lsla$acc_id==id])
wj32 <- append(wj31, wj3$total[wj3$ID==id])
age2 <- append(age1, scf$age[scf$ID==id])}

d1 <- data.frame(tsl_rt_slope,vsl_rt_slope,ssl_rt_slope,lsl_rt_slope)
d2 <- data.frame(tsl_accuracy,ssl_accuracy,vsl_accuracy,lsl_accuracy)
chart.Correlation(d1, histogram=TRUE, pch=19)
chart.Correlation(d2, histogram=TRUE, pch=19)


```


#Anova analysis
## RT Slope
```{r,echo=FALSE,warning=FALSE}
rts <- read.csv("C:/Users/Qlab/Downloads/mturk_data/anova_data.csv")
rts_anova <- aov(Score~Modality*Domain + Error(ID/(Modality*Domain)),data=rts)
summary(rts_anova)
```

##Accuracy
```{r,echo=FALSE,warning=FALSE}
acc <- read.csv("C:/Users/Qlab/Downloads/mturk_data/anova_acc_data.csv")
acc_anova <- aov(Accuracy~Modality*Domain + Error(ID/(Modality*Domain)),data=acc)
summary(acc_anova)
```
