---
title: "blast_fmri_clean_file"
author: "Jojo Hu"
date: "9/23/2022"
output: html_document
---

# TO DO: Delete what is already in these folders

# Clean and move adult files
```{r}
library(stringr)

aliceFile <-
  list.files("/Volumes/data/projects/blast/data/derivatives/fitlins/analyzed/fitlins_alice", 
           pattern = "sub*", 
           full.names = T, recursive = F)

aliceFile <-
  list.files(aliceFile,
           pattern = "level-run_name-runlevel_sub-blasta\\d+_run-\\d+_contrast-intactGtDegraded_stat-z_statmap.nii", 
           full.names = T, recursive = F)

aliceFile <- as.data.frame(aliceFile)

aliceFile$aliceFile <- as.character(aliceFile$aliceFile)

aliceFile$basename <- basename(as.character(aliceFile$aliceFile))

aliceFile$part_id <- str_extract(aliceFile$basename, "sub-blasta[[:digit:]]+")

aliceFile$bare_id <- str_extract(aliceFile$basename, "(?<=sub-blasta)[[:digit:]]+")

aliceFile$run <- str_extract(aliceFile$basename, "(?<=run-)[[:digit:]]")

aliceFile$bare_run <- paste0(aliceFile$bare_id, "_", aliceFile$run)

aliceFile <- 
  aliceFile %>%
  arrange(aliceFile)

aliceFile$rename_id <- paste0(seq(1:nrow(aliceFile)), "_stat-z_statmap.nii.gz")

aliceFile$rename_number <- seq(1:nrow(aliceFile))

aliceFile$new_path <- paste0("/Volumes/data/projects/blast/data/mri/imaging/scott_gcss_lpsa/data/langloc_fitlins/adult/",
                             aliceFile$basename)

aliceFile$new_name <- paste0("/Volumes/data/projects/blast/data/mri/imaging/scott_gcss_lpsa/data/langloc_fitlins/adult/",
                             aliceFile$rename_id)

aliceFile$format_id <- paste("blast", str_extract(aliceFile$part_id, "(?<=blast)\\S{1}"), str_extract(aliceFile$part_id, "(?<=blasta)\\S+"), sep = "_")

aliceFileAd <- aliceFile

file.copy(as.character(aliceFile$aliceFile), aliceFile$new_path, overwrite = T)

file.rename(aliceFile$new_path, aliceFile$new_name)

write.csv(aliceFile, 
          "/Volumes/data/projects/blast/data/mri/imaging/scott_gcss_lpsa/data/langloc_fitlins/renamed_id_adult.csv", row.names = F)

my_output <- capture.output(write.table(aliceFile[, "bare_run"], sep = " ", col.names = F, row.names = F, quote = F, eol = "\n"))
writeBin(paste(my_output, collapse = "\n"),  "/Volumes/data/projects/blast/data/mri/imaging/scott_gcss_lpsa/data/langloc_fitlins/langloc_adult.txt")
```


# Clean and move children files
```{r}
library(stringr)

aliceFile <-
  list.files("/Volumes/data/projects/blast/data/derivatives/fitlins/analyzed/fitlins_alice", 
           pattern = "sub*", 
           full.names = T, recursive = F)

aliceFile <-
  list.files(aliceFile,
           pattern = "level-run_name-runlevel_sub-blastc\\d+_run-\\d+_contrast-intactGtDegraded_stat-z_statmap.nii", 
           full.names = T, recursive = F)

aliceFile <- as.data.frame(aliceFile)

aliceFile$aliceFile <- as.character(aliceFile$aliceFile)

aliceFile$basename <- basename(as.character(aliceFile$aliceFile))

aliceFile$part_id <- str_extract(aliceFile$basename, "sub-blastc[[:digit:]]+")

aliceFile$bare_id <- str_extract(aliceFile$basename, "(?<=sub-blastc)[[:digit:]]+")

aliceFile$run <- str_extract(aliceFile$basename, "(?<=run-)[[:digit:]]")

aliceFile$bare_run <- paste0(aliceFile$bare_id, "_", aliceFile$run)

aliceFile <- 
  aliceFile %>%
  arrange(aliceFile) %>%
  distinct(.) %>%
  #In case any archive files are read in; shouldn't be though
  filter(!str_detect(aliceFile, "archive")) %>%
  dplyr::mutate(rename_id = paste0(1:n(), "_stat-z_statmap.nii.gz"),
                rename_number = 1:n())

# Read in TD subject list
tdID <- read.csv("/Users/jojohu/Downloads/Blast_mri_cumulative_data.xlsx - TD.csv")

aliceFile$format_id <- paste("blast", str_extract(aliceFile$part_id, "(?<=blast)\\S{1}"), str_extract(aliceFile$part_id, "(?<=blastc)\\S+"), sep = "_")

aliceFile <- 
  aliceFile %>%
  filter(format_id %in% unique(tdID$ID)) %>%
  distinct(.)

aliceFile$new_path <- paste0("/Volumes/data/projects/blast/data/mri/imaging/scott_gcss_lpsa/data/langloc_fitlins/child/td/",
                             aliceFile$basename)

aliceFile$new_name <- paste0("/Volumes/data/projects/blast/data/mri/imaging/scott_gcss_lpsa/data/langloc_fitlins/child/td/",
                             aliceFile$rename_id)

aliceFileTD <- aliceFile

file.copy(as.character(aliceFile$aliceFile), aliceFile$new_path, overwrite = T)

file.rename(aliceFile$new_path, aliceFile$new_name)

write.csv(aliceFile, 
          "/Volumes/data/projects/blast/data/mri/imaging/scott_gcss_lpsa/data/langloc_fitlins/renamed_id_child.csv", row.names = F)

my_output <- capture.output(write.table(aliceFile[, "bare_run"], sep = " ", col.names = F, row.names = F, quote = F, eol = "\n"))
writeBin(paste(my_output, collapse = "\n"),  "/Volumes/data/projects/blast/data/mri/imaging/scott_gcss_lpsa/data/langloc_fitlins/langloc_child.txt")
```

# Save combined dataset
```{r}
aliceCombined <-
  dplyr::bind_rows(aliceFileAd, aliceFileTD) %>%
  distinct(.) %>%
  arrange(aliceFile) %>%
  #In case any archive files are read in; shouldn't be though
  filter(!str_detect(aliceFile, "archive")) %>%
  dplyr::mutate(rename_id = paste0(1:n(), "_stat-z_statmap.nii.gz"),
                rename_number = 1:n())

aliceCombined$new_path <- paste0("/Volumes/data/projects/blast/data/mri/imaging/scott_gcss_lpsa/data/langloc_fitlins/combined/td_adult/", 
                                 aliceCombined$basename)

aliceCombined$new_name <- paste0("/Volumes/data/projects/blast/data/mri/imaging/scott_gcss_lpsa/data/langloc_fitlins/combined/td_adult/",  
                                 aliceCombined$rename_id)

file.copy(as.character(aliceCombined$aliceFile), aliceCombined$new_path, overwrite = F)

```






```{r}
file.rename(aliceCombined$new_path, aliceCombined$new_name)

write.csv(aliceCombined, 
          "/Volumes/data/projects/blast/data/mri/imaging/scott_gcss_lpsa/data/langloc_fitlins/renamed_id_combined.csv", row.names = F)

my_output <- capture.output(write.table(aliceCombined[, "bare_run"], sep = " ", col.names = F, row.names = F, quote = F, eol = "\n"))
writeBin(paste(my_output, collapse = "\n"),  "/Volumes/data/projects/blast/data/mri/imaging/scott_gcss_lpsa/data/langloc_fitlins/langloc_combined.txt")
```









