#!/bin/bash
# the default umask is 002
#Project specific environments
source /home/qigroup/project_list

#Source anaconda2,  matlab
PATH=/home/qigroup/anaconda2/bin:/usr/local/MATLAB/R2018b/bin:$PATH
#FSL and Freesurfer are installed for the system. Please take a look at the version number at /usr/local/

# Setup project specific subj dir
export SUBJECTS_DIR=/home/qigroup/Documents/projects/blast/higher_level_analysis/freesurfer
# Setup project specific conda python environments
export CONDA_ENVS_PATH=/home/qigroup/Documents/projects/conda_env
source activate blast

export project_name="blast"
