---
title: "adult_web_sl_aggregate.rmd"
author: "Jojo Hu"
date: "1/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
#Read in SL files that have data on NAS-------------------------------------------------------
input_path <- "/Users/jojohu/Documents/Qlab/blast_online_data/data_summaries/blast_online_adult/breakdown"


acc_files <- list.files(path =input_path,
              pattern = "*accuracies.csv", full.names = T)

rt_files <- list.files(path =input_path,
                       pattern = "*rts.csv", full.names = T)

entropy_files <- list.files(path =input_path,
                            pattern = "*entropy.csv", full.names = T)


#---------------------------------------------------------------------------------------------



#Read the names and content for each BLAST file
acc_file_name <- lapply(acc_files, basename)
acc_files <- lapply(acc_files, read.csv)

rt_file_name <- lapply(rt_files, basename)
rt_files <- lapply(rt_files, read.csv)

entropy_file_name <- lapply(entropy_files, basename)
entropy_files <- lapply(entropy_files, read.csv)


#---------------------------------------------------------------------------------------------



#Function to put the name of the file into a third column of that file-----------------------
library("stringr")
add_name_files <- list()

add_task_name <- 
function (file_name, files) {
  for (i in 1:length(files)) {
    current_file_name <- file_name[[i]]
    current_file_name <-
      str_extract(current_file_name, "(?<=blast_online_)\\S+(?=.csv)")
    files[[i]]$task <- current_file_name
    add_name_files[[i]] <- files[[i]]
  }
  return(add_name_files)
}


#Blast data put name into third column--------------------------------------------------------------------------------
acc_data <- list()
rt_data <- list()
entropy_data <- list()

acc_data <- add_task_name(acc_file_name, acc_files)
rt_data <- add_task_name(rt_file_name, rt_files)
entropy_data <- add_task_name(entropy_file_name, entropy_files)


#RT data have different length of columns
#Blast extract only relevant RT columns--------------------------------------------------------------------
for (i in 1:length(rt_data)) {
  rt_data[[i]] <- 
    rt_data[[i]][, c("par_id", "mean_rt", "scaled_rt_slope", "task")]
}


#Combine all the files (each measure, rbind to one file)--------------------------------------------------------
#Combine blast files into one file
acc_data <- do.call(rbind, acc_data)
rt_data <- do.call(rbind, rt_data)
entropy_data <- do.call(rbind, entropy_data)


write.csv(acc_data, "/Users/jojohu/Documents/Qlab/bucld_2019_followup/acc_data_blast_adult.csv")
write.csv(rt_data, "/Users/jojohu/Documents/Qlab/bucld_2019_followup/rt_data_blast_adult.csv")
write.csv(entropy_data, "/Users/jojohu/Documents/Qlab/bucld_2019_followup/entropy_data_blast_adult.csv")
```




